In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 

In [2]:
dataset = pd.read_csv('train.csv')
selected_columns = ['PassengerId','Pclass','Embarked','Sex', 'Age', 'SibSp', 'Parch', 'Fare']
x = dataset[selected_columns]
y = dataset.iloc[:,1]

In [3]:
data = pd.read_csv('test.csv')
columns = ['PassengerId','Pclass','Embarked','Sex','Age','SibSp','Parch','Fare',]
x_test = data[columns]

In [5]:
print(x_test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Embarked     418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Fare         417 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 26.3+ KB
None


In [6]:
print(x.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Pclass       891 non-null    int64  
 2   Embarked     889 non-null    object 
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Fare         891 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB
None


In [8]:
print(y.info())

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: Survived
Non-Null Count  Dtype
--------------  -----
891 non-null    int64
dtypes: int64(1)
memory usage: 7.1 KB
None


Missing data handle

In [13]:
mean_age = x['Age'].mean()
mean_1 = x_test['Age'].mean()
mean_2 = x_test['Fare'].mean()

floored_mean_age = np.floor(mean_age)
floored_1 = np.floor(mean_1)
floored_2 = np.floor(mean_2)

x.loc[:, 'Age'] = x['Age'].fillna(floored_mean_age)
x_test.loc[:, 'Age'] = x_test['Age'].fillna(floored_1)
x_test.loc[:, 'Fare'] = x_test['Fare'].fillna(floored_2)


In [14]:
print(x)
print(x_test)

     PassengerId  Pclass Embarked     Sex   Age  SibSp  Parch     Fare
0              1       3        S    male  22.0      1      0   7.2500
1              2       1        C  female  38.0      1      0  71.2833
2              3       3        S  female  26.0      0      0   7.9250
3              4       1        S  female  35.0      1      0  53.1000
4              5       3        S    male  35.0      0      0   8.0500
..           ...     ...      ...     ...   ...    ...    ...      ...
886          887       2        S    male  27.0      0      0  13.0000
887          888       1        S  female  19.0      0      0  30.0000
888          889       3        S  female  29.0      1      2  23.4500
889          890       1        C    male  26.0      0      0  30.0000
890          891       3        Q    male  32.0      0      0   7.7500

[891 rows x 8 columns]
     PassengerId  Pclass Embarked     Sex   Age  SibSp  Parch      Fare
0            892       3        Q    male  34.5     

In [15]:
x = x.to_numpy()

In [16]:
x_test = x_test.to_numpy()

In [17]:
print(x)

[[1 3 'S' ... 1 0 7.25]
 [2 1 'C' ... 1 0 71.2833]
 [3 3 'S' ... 0 0 7.925]
 ...
 [889 3 'S' ... 1 2 23.45]
 [890 1 'C' ... 0 0 30.0]
 [891 3 'Q' ... 0 0 7.75]]


In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2,3])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
x_test = np.array(ct.transform(x_test))

In [19]:
print(x)
print(x_test)

[[0.0 0.0 1.0 ... 1 0 7.25]
 [1.0 0.0 0.0 ... 1 0 71.2833]
 [0.0 0.0 1.0 ... 0 0 7.925]
 ...
 [0.0 0.0 1.0 ... 1 2 23.45]
 [1.0 0.0 0.0 ... 0 0 30.0]
 [0.0 1.0 0.0 ... 0 0 7.75]]
[[0.0 1.0 0.0 ... 0 0 7.8292]
 [0.0 0.0 1.0 ... 1 0 7.0]
 [0.0 1.0 0.0 ... 0 0 9.6875]
 ...
 [0.0 0.0 1.0 ... 0 0 7.25]
 [0.0 0.0 1.0 ... 0 0 8.05]
 [1.0 0.0 0.0 ... 1 1 22.3583]]


In [20]:
x_df = pd.DataFrame(x)
x_df.to_csv('transformed_data.csv', index=False)

In [21]:
print(x_df.head())

    0    1    2    3    4    5  6  7     8  9  10       11
0  0.0  0.0  1.0  0.0  0.0  1.0  1  3  22.0  1  0     7.25
1  1.0  0.0  0.0  0.0  1.0  0.0  2  1  38.0  1  0  71.2833
2  0.0  0.0  1.0  0.0  1.0  0.0  3  3  26.0  0  0    7.925
3  0.0  0.0  1.0  0.0  1.0  0.0  4  1  35.0  1  0     53.1
4  0.0  0.0  1.0  0.0  0.0  1.0  5  3  35.0  0  0     8.05


In [49]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score, roc_curve


In [44]:
# Define classifiers and pipelines
classifiers = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Random Forest': RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42),
    'Support Vector Machine': SVC(probability=True, random_state=42),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators=100, random_state=42)
}

In [46]:
from sklearn.model_selection import train_test_split
x_train, X_test, y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [54]:
metrics = {}
for name, model in classifiers.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(Y_test, y_pred)
    roc_auc = roc_auc_score(Y_test, y_pred)
    
    metrics[name] = {'accuracy': accuracy, 'roc_auc': roc_auc}
    print(f'{name}: Accuracy = {accuracy:.4f}, ROC AUC = {roc_auc:.4f}')

d:\Python\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression: Accuracy = 0.8045, ROC AUC = 0.7954
Random Forest: Accuracy = 0.8101, ROC AUC = 0.7942
Support Vector Machine: Accuracy = 0.5978, ROC AUC = 0.5175
K-Nearest Neighbors: Accuracy = 0.6648, ROC AUC = 0.6265
Decision Tree: Accuracy = 0.7765, ROC AUC = 0.7656
Gradient Boosting: Accuracy = 0.8212, ROC AUC = 0.8097


In [55]:
best_model_name = max(metrics, key=lambda k: (metrics[k]['accuracy'], metrics[k]['roc_auc']))
classifier = classifiers[best_model_name]
print(f'The best model is {best_model_name} with Accuracy = {metrics[best_model_name]["accuracy"]:.4f} and ROC AUC = {metrics[best_model_name]["roc_auc"]:.4f}')

The best model is Gradient Boosting with Accuracy = 0.8212 and ROC AUC = 0.8097


In [23]:
x_test_df = pd.DataFrame(x_test)

In [24]:
print(x_test_df)

      0    1    2    3    4    5     6  7     8  9  10       11
0    0.0  1.0  0.0  0.0  0.0  1.0   892  3  34.5  0  0   7.8292
1    0.0  0.0  1.0  0.0  1.0  0.0   893  3  47.0  1  0      7.0
2    0.0  1.0  0.0  0.0  0.0  1.0   894  2  62.0  0  0   9.6875
3    0.0  0.0  1.0  0.0  0.0  1.0   895  3  27.0  0  0   8.6625
4    0.0  0.0  1.0  0.0  1.0  0.0   896  3  22.0  1  1  12.2875
..   ...  ...  ...  ...  ...  ...   ... ..   ... .. ..      ...
413  0.0  0.0  1.0  0.0  0.0  1.0  1305  3  30.0  0  0     8.05
414  1.0  0.0  0.0  0.0  1.0  0.0  1306  1  39.0  0  0    108.9
415  0.0  0.0  1.0  0.0  0.0  1.0  1307  3  38.5  0  0     7.25
416  0.0  0.0  1.0  0.0  0.0  1.0  1308  3  30.0  0  0     8.05
417  1.0  0.0  0.0  0.0  0.0  1.0  1309  3  30.0  1  1  22.3583

[418 rows x 12 columns]


In [25]:
x_test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       418 non-null    object
 1   1       418 non-null    object
 2   2       418 non-null    object
 3   3       418 non-null    object
 4   4       418 non-null    object
 5   5       418 non-null    object
 6   6       418 non-null    object
 7   7       418 non-null    object
 8   8       418 non-null    object
 9   9       418 non-null    object
 10  10      418 non-null    object
 11  11      418 non-null    object
dtypes: object(12)
memory usage: 39.3+ KB


In [56]:
predictions = classifier.predict(x_test)

In [57]:
predictions = np.round(predictions).astype(int)

In [58]:
print(x)

[[0.0 0.0 1.0 ... 1 0 7.25]
 [1.0 0.0 0.0 ... 1 0 71.2833]
 [0.0 0.0 1.0 ... 0 0 7.925]
 ...
 [0.0 0.0 1.0 ... 1 2 23.45]
 [1.0 0.0 0.0 ... 0 0 30.0]
 [0.0 1.0 0.0 ... 0 0 7.75]]


In [59]:
print(x_test_df.head())

    0    1    2    3    4    5    6  7     8  9  10       11
0  0.0  1.0  0.0  0.0  0.0  1.0  892  3  34.5  0  0   7.8292
1  0.0  0.0  1.0  0.0  1.0  0.0  893  3  47.0  1  0      7.0
2  0.0  1.0  0.0  0.0  0.0  1.0  894  2  62.0  0  0   9.6875
3  0.0  0.0  1.0  0.0  0.0  1.0  895  3  27.0  0  0   8.6625
4  0.0  0.0  1.0  0.0  1.0  0.0  896  3  22.0  1  1  12.2875


In [60]:
passenger_ids = x_test[:,6]

In [61]:
submission_df = pd.DataFrame({
    'Passenger Id': passenger_ids,
    'Survived': predictions
})

# Step 3: Save to CSV
submission_df.to_csv('submission2.csv', index=False)